#!/bin/bash

init()
{
	ERWIZ_HOME=$(pwd)
	PACKAGE_HOME=${ERWIZ_HOME}/package
	BUILD_PATH=`readlink -f $0`
	BUILD_PATH=`dirname $BUILD_PATH`
	cd $BUILD_PATH

	# if the last property has not newline it's not read
	#while IFS=$'\r=' read -r key value _; 
	#do 
	#	case $key in 
	#		app.name*) appname=$value;; 
	#		app.version) appversion=$value;; 
	#	esac; 
	#done < ${ERWIZ_HOME}/app_info.properties; 
	#echo "$appname-$appversion"	
	
	app_name="$(sed '/^\#/d' ${ERWIZ_HOME}/app_info.properties | grep 'app.name'  | tail -n 1 | cut -d "=" -f2-)"
	app_version="$(sed '/^\#/d' ${ERWIZ_HOME}/app_info.properties | grep 'app.version'  | tail -n 1 | cut -d "=" -f2-)"
}

clean()
{
	echo "clean() to be implemented"
	rm -rf ${app_name}*
}

package()
{
	#echo "package() to be implemented"
	
	echo "cp -R ${PACKAGE_HOME}/bin ${app_name}"
	cp -R ${PACKAGE_HOME}/bin ${app_name}-${app_version}
	cp -R template ${app_name}-${app_version}
	cd ${app_name}-${app_version}
	mv template debian
	mv license.txt copyright
	mv readme.txt readme
	mv authors.txt authors
	fakeroot dh binary-indep
}

post_clean()
{
	cd $BUILD_PATH
	rm -rf ${app_name}-${app_version}
}

init
clean
package
post_clean