#!/bin/bash

init()
{
	ERWIZ_HOME=$(pwd)
	PACKAGE_HOME=${ERWIZ_HOME}/package
	BUILD_PATH=`readlink -f $0`
	BUILD_PATH=`dirname $BUILD_PATH`
	cd $BUILD_PATH

	# if the last property has not newline it's not read
	#while IFS=$'\r=' read -r key value _; 
	#do 
	#	case $key in 
	#		app.name*) appname=$value;; 
	#		app.version) appversion=$value;; 
	#	esac; 
	#done < ${ERWIZ_HOME}/app_info.properties; 
	#echo "$appname-$appversion"	
	
	app_name="$(sed '/^\#/d' ${ERWIZ_HOME}/app_info.properties | grep 'app.name'  | tail -n 1 | cut -d "=" -f2-)"
	app_version="$(sed '/^\#/d' ${ERWIZ_HOME}/app_info.properties | grep 'app.version'  | tail -n 1 | cut -d "=" -f2-)"
}

clean()
{
	rm -rf ${app_name}* pkg src
}

package()
{
	cp ../../single/${app_name}-${app_version}-bin.tar.gz .	
	md5=$(md5sum ${app_name}-${app_version}-bin.tar.gz | cut -d ' ' -f 1)
	
	echo "sed -i \"s/^md5sums=(\(.*\))/\md5sums=(${md5})/g\" PKGBUILD"
	sed -i "s/^md5sums=(\(.*\))/\md5sums=(${md5})/g" PKGBUILD
	
	echo "sed -i \"s/^pkgver=\(.*\)/\pkgver=(${app_version})/g\" PKGBUILD"
	sed -i "s/^pkgver=\(.*\)/\pkgver=(${app_version})/g" PKGBUILD

	makepkg --source
}

post_clean()
{
	rm -rf ${app_name}-${app_version}-bin* pkg src
}

init
clean
package
post_clean